
package com.insonix.wsdltest;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PersonService", targetNamespace = "http://impl.cxf.insonix.com/", wsdlLocation = "http://insonix-cxf.sunnydyal.cloudbees.net/services/person?wsdl")
public class PersonService_Service
    extends Service
{

    private final static URL PERSONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.insonix.wsdltest.PersonService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.insonix.wsdltest.PersonService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://insonix-cxf.sunnydyal.cloudbees.net/services/person?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://insonix-cxf.sunnydyal.cloudbees.net/services/person?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PERSONSERVICE_WSDL_LOCATION = url;
    }

    public PersonService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonService_Service() {
        super(PERSONSERVICE_WSDL_LOCATION, new QName("http://impl.cxf.insonix.com/", "PersonService"));
    }

    /**
     * 
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort() {
        return super.getPort(new QName("http://impl.cxf.insonix.com/", "PersonServiceImplPort"), PersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.cxf.insonix.com/", "PersonServiceImplPort"), PersonService.class, features);
    }

}
