/**
 * This class is generated by jOOQ
 */
package com.the13star.dbmetadata.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetail extends org.jooq.impl.TableImpl<com.the13star.dbmetadata.tables.records.UserDetailRecord> {

	private static final long serialVersionUID = -1067136128;

	/**
	 * The singleton instance of <code>jooq_test.user_detail</code>
	 */
	public static final com.the13star.dbmetadata.tables.UserDetail USER_DETAIL = new com.the13star.dbmetadata.tables.UserDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.the13star.dbmetadata.tables.records.UserDetailRecord> getRecordType() {
		return com.the13star.dbmetadata.tables.records.UserDetailRecord.class;
	}

	/**
	 * The column <code>jooq_test.user_detail.id</code>.
	 */
	public final org.jooq.TableField<com.the13star.dbmetadata.tables.records.UserDetailRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jooq_test.user_detail.name</code>.
	 */
	public final org.jooq.TableField<com.the13star.dbmetadata.tables.records.UserDetailRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>jooq_test.user_detail.age</code>.
	 */
	public final org.jooq.TableField<com.the13star.dbmetadata.tables.records.UserDetailRecord, java.lang.Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>jooq_test.user_detail</code> table reference
	 */
	public UserDetail() {
		this("user_detail", null);
	}

	/**
	 * Create an aliased <code>jooq_test.user_detail</code> table reference
	 */
	public UserDetail(java.lang.String alias) {
		this(alias, com.the13star.dbmetadata.tables.UserDetail.USER_DETAIL);
	}

	private UserDetail(java.lang.String alias, org.jooq.Table<com.the13star.dbmetadata.tables.records.UserDetailRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserDetail(java.lang.String alias, org.jooq.Table<com.the13star.dbmetadata.tables.records.UserDetailRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.the13star.dbmetadata.JooqTest.JOOQ_TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.the13star.dbmetadata.tables.records.UserDetailRecord> getPrimaryKey() {
		return com.the13star.dbmetadata.Keys.KEY_USER_DETAIL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.the13star.dbmetadata.tables.records.UserDetailRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.the13star.dbmetadata.tables.records.UserDetailRecord>>asList(com.the13star.dbmetadata.Keys.KEY_USER_DETAIL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.the13star.dbmetadata.tables.UserDetail as(java.lang.String alias) {
		return new com.the13star.dbmetadata.tables.UserDetail(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.the13star.dbmetadata.tables.UserDetail rename(java.lang.String name) {
		return new com.the13star.dbmetadata.tables.UserDetail(name, null);
	}
}
