/**
 * This class is generated by jOOQ
 */
package com.the13star.dbmetadata;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>jooq_test</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.the13star.dbmetadata.tables.records.UserDetailRecord> KEY_USER_DETAIL_PRIMARY = UniqueKeys0.KEY_USER_DETAIL_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.the13star.dbmetadata.tables.records.UserDetailRecord> KEY_USER_DETAIL_PRIMARY = createUniqueKey(com.the13star.dbmetadata.tables.UserDetail.USER_DETAIL, com.the13star.dbmetadata.tables.UserDetail.USER_DETAIL.ID);
	}
}
