/**
 * This class is generated by jOOQ
 */
package com.the13star.dbmetadata;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in jooq_test
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq_test.user_detail
	 */
	public static final com.the13star.dbmetadata.tables.UserDetail USER_DETAIL = com.the13star.dbmetadata.tables.UserDetail.USER_DETAIL;
}
